/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type Role = 'ADMIN' | 'TEACHER' | 'STUDENT' | 'PARENT';

export type ClassGrade = '9th' | '10th' | '11th' | '12th' | 'Library';

export interface User {
  id: string;
  username: string; // This is the unique login ID generated by Admin
  name: string;
  role: Role;
  createdAt: string;
}

export interface AdminUser extends User {
  role: 'ADMIN';
}

export interface TeacherUser extends User {
  role: 'TEACHER';
  subjects: string[];
  classes: ClassGrade[];
}

export interface StudentUser extends User {
  role: 'STUDENT';
  classGrade: ClassGrade;
  parentId?: string; // Linked parent account ID
  studentIdCardNum: string; // Admin generated enrollment card num
  seatNumber?: string; // Active library seat/bench designation
  benchNumber?: string;
  // Fee Structure & Pending Details
  totalFee: number;
  paidFee: number;
  pendingFee: number;
  paymentStatus: 'PAID' | 'PARTIAL' | 'PENDING';
}

export interface ParentUser extends User {
  role: 'PARENT';
  childId?: string; // Linked child Student ID
  childName?: string;
  childClass?: ClassGrade;
  relationship: string; // e.g. Father, Mother, Guardian
  mobileNumber?: string;
}

export interface StudyMaterial {
  id: string;
  title: string;
  description: string;
  classGrade: ClassGrade;
  subject: string;
  fileName: string;
  fileSize: string;
  fileContent: string; // Encrypted content string (Base64-like simulating ciphertext)
  uploadedBy: string; // Teacher name
  uploadedAt: string;
}

export interface Assignment {
  id: string;
  title: string;
  description: string;
  classGrade: ClassGrade;
  subject: string;
  dueDate: string;
  uploadedBy: string; // Teacher ID
  teacherName: string;
  uploadedAt: string;
}

export interface Submission {
  id: string;
  assignmentId: string;
  assignmentTitle: string;
  studentId: string;
  studentName: string;
  classGrade: ClassGrade;
  submittedAt: string;
  submittedContent: string; // Encrypted student answer content
  status: 'SUBMITTED' | 'GRADED';
  grade?: string; // e.g. A, B, C, 95%
  feedback?: string; // Feedback from teacher
  fileName?: string;
  fileSize?: string;
}

export interface CommunicationMessage {
  id: string;
  senderId: string;
  senderName: string;
  senderRole: Role;
  receiverId: string;
  receiverName: string;
  receiverRole: Role;
  content: string; // Encrypted message content
  timestamp: string;
}

export interface Notification {
  id: string;
  recipientId: string; // "ALL_TEACHERS", "ALL_STUDENTS", or specific userId
  title: string;
  message: string;
  type: 'INFO' | 'ASSIGNMENT' | 'SUBMISSION' | 'GRADE' | 'MESSAGE' | 'SECURITY';
  timestamp: string;
  read: boolean;
}

export interface ActivityLog {
  id: string;
  userId: string;
  userName: string;
  userRole: Role;
  action: string;
  timestamp: string;
  ipAddress: string;
}

export interface TimetableEntry {
  id: string;
  classGrade: ClassGrade;
  day: string; // 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday'
  timeSlot: string; // e.g. "09:00 AM - 10:00 AM"
  subject: string;
  teacherName: string;
}

export type AttendanceStatus = 'PRESENT' | 'ABSENT' | 'LATE' | 'EXCUSED';

export interface AttendanceRecord {
  id: string;
  studentId: string;
  studentName: string;
  classGrade: ClassGrade;
  date: string; // YYYY-MM-DD
  status: AttendanceStatus;
  markedBy: string; // Teacher User ID
  teacherName: string;
  subject: string;
  remarks?: string;
}

